New media supported
bmaupin/go-epub pull request #45
Opened 2021-08-23 12:29 UTC by owulveryck

### This PR introduces a support for inline-media (dataurl encoded).
To achieve this feature, there is a need to `tweak` the writeMedia method.
To make things maintainable and testable, instead of overloading the method, I created an external function to fetch the media.
This function relies on sub-functions with this signature:

```go
func(string) (io.ReadCloser, error)
```

Three subfunctions are implemented:
- `fetchMediaFromURL` fetches a media from a URL (the standard behaviour)
- `fetchMediaLocally` get the media from the local FR
- `fetchMediaDataURL` fetch the media from a RFC 2397 encoded scheme

The main `fetchMedia` function tries all of the functions and stop when one exist without error. If non of them exist without error, the `FileRetrievalError` error is raised containing all the errors of all the checks for analysis.

As requested, a set of unit-test has been added to maintain the test coverage.

2021-08-23 17:34 UTC, bmaupin commented
C'est génial, ça ! I love how it removes the need for hardcoding the mime types. I think this should also close #8.

 I'll review the code and make any additional comments there.

Merci !

2021-08-24 06:17 UTC, owulveryck commented
I have used the [`TempDir`](https://pkg.go.dev/testing#T.TempDir) method which has been introduced in go 1.15.
The tests are the reason why the CI is failing :D 

Do you have a policy regarding the Go versions you want to support? Is Go < 1.15 still a target ?
If so, I need to tweak the test in order to use ioutil.Tmpdir instead.

2021-08-24 11:40 UTC, bmaupin requested changes
> I have used the [`TempDir`](https://pkg.go.dev/testing#T.TempDir) method which has been introduced in go 1.15.
> The tests are the reason why the CI is failing :D
> 
> Do you have a policy regarding the Go versions you want to support? Is Go < 1.15 still a target ?
> If so, I need to tweak the test in order to use ioutil.Tmpdir instead.

I don't have an explicit policy; I did a quick search to see if there was a best practice regarding supporting older versions of Go, but I wasn't able to find one. In the past I know some server distros such as RHEL typically package older versions of programming languages. From a general sense, since this is a library it seems like it would be good to support the earliest Go release that we reasonably can. 

However, I didn't take a good look yesterday at the differences between the two functions and `TempDir` from `testing` looks a lot more convenient than the one from `ioutil`. Also, apparently only the last two Go releases are officially supported. So I think I would be okay dropping support for Go < 1.15.

So maybe we could:

1. Remove the `TODO` if it's no longer necessary
2. Update `go.mod` to `go 1.15` (I'm not sure why it's `go 1.16`)
3. Update the tests to remove versions < 1.15

How does that sound?

Thanks!

2021-08-24 12:39 UTC, owulveryck commented
Regarding the support of Go version, the policy we use for Gorgonia (gorgonia.org) is to support the stable version and the n-1 stable version. This means being able to wait for a year before requiring updates. (https://github.com/gorgonia/gorgonia#go-version-support) 

We tend to update the CI accordingly when a new version is released.

2021-08-24 12:42 UTC, owulveryck commented on go.mod
> +go 1.16
There is no particular reason.
I had to run a `go get` to include the newer dependencies. This has updated the go.mod with the version of go I am using in my dev environment.

2021-08-24 12:46 UTC, owulveryck commented on fetchmedia_test.go
> +				mediaFolderPath: t.TempDir(),
It is up to you as a maintainer to choose the supporting policy.
My experience is that it is not really important to support older versions of Go.
Most application use bleeding-edge version of Go for their releases, and the promise for backward compatibility of the language ensure that upgrading the Go toolkit will not break anything.

2021-08-24 12:56 UTC, owulveryck commented on fetchmedia_test.go
> +		// TODO: Add test cases.
Fixed

2021-08-24 16:50 UTC, bmaupin commented
Looks good, thanks! I'll make the remaining changes.

2021-08-24 16:58 UTC, bmaupin approved these changes

2021-08-24 17:05 UTC, merged