Image shows from files inside of epub
bmaupin/go-epub pull request #65
Opened 2023-08-04 13:22 UTC by Monirzadeh

This PR add a method name `EmbeddedImages()` that download image inside the `xhtml` than change EPUB to load show from included images instead of URL.
Maybe close #26

2023-08-08 18:02 UTC, bmaupin commented
After chewing on it for a couple minutes, I'm thinking that having this as a separate method (the way it currently is) is probably the simplest approach. I do think `EmbeddedImages` should probably be renamed, maybe to just `EmbedImages` because I think the standard practice is that method names should be verbs.

But I'd still be curious to hear if there are any other thoughts.

2023-08-08 19:53 UTC, bmaupin commented
I suppose it could even be a parameter of the constructor to apply it to the whole Epub. But either way I think it's too much to refactor all of that now, so it makes the most sense to have this as a separate method.

2023-08-08 20:41 UTC, bmaupin requested changes

2023-08-09 17:58 UTC, bmaupin commented on epub.go
> +// Just call EmbedImages() after section added
This looks great! one last question: do you think it's worth mentioning in the documentation for this method that it won't return an error if any of the images fail to download?

2023-08-10 16:51 UTC, bmaupin commented
I merged #66 and rebased your work on top of it just to make sure the tests are passing. Unfortunately this seems to be failing on the Windows runner.

I think it might be related to #19.

Would you mind taking a look?

Thanks!

2023-08-14 18:13 UTC, owulveryck commented
I will have a look by the end of this week.

2023-08-16 12:16 UTC, owulveryck commented
LGTM

2023-08-16 12:18 UTC, merged